### ISSUE TITLE
Magister API changes?

### ISSUE THREAD

**Issue by robbertkl** [Stanvk/Magister#15]
For a little while now (maybe a week?) I'm getting issues from this library, even though it was working perfectly before and no changes were made. After updating to the latest release, it still won't work.

The underlying problem seems to be a 404 response to the POST to `/api/sessie`, which seems to suggest an API change on the Magister side. I'm not sure if this applies to all schools already, or just the one I'm using (stanislas.magister.net).

It seems the JavaScript implementation (https://github.com/simplyGits/MagisterJS) does still work. It's using a POST to `/api/sessies` instead, but it looks like it also needs an application/json POST body.

Any idea if the API has changed recently?

**Comment by Kickwood** [comment]
This is probably unique to that school as I've never seen this problem anywhere else. I tried opening stanislas.magister.net/api/sessie in the browser and indeed, that doesn't work. You could try to edit the `ElegantUserProvider` file inside the auth service real quick and change this line:

``` php
$this->client->post('sessie', $body);
```

to this:

``` php
$this->client->post('sessies', $body);
```

and tell me if that fixed the problem.

**Comment by robbertkl** [comment]
Yeah, that's what I've tried already, but then it's rejecting my username/password (which were working previously). My guess is that's because it is expecting a JSON POST with the username/password.

By the way, the school I'm using has Magister version 6.0.24 (visible on the login screen). Is yours the same?

**Comment by Kickwood** [comment]
The Magister version is the same.

You could use the http service and play with certain values yourself, e.g:

``` php
$magister = new Magister\Magister('stanislas');

$credentials = [
  'Gebruikersnaam' => 'Foo',
  'Wachtwoord' => 'Bar'
];

$request = Http::post('sessies', ['body' => $credentials])->json();

var_dump($request);
```

Which outputs:

```
Ongeldig account of verkeerde combinatie van gebruikersnaam en wachtwoord. Probeer het nog eens of neem contact op met de applicatiebeheerder van de school.
```

There might be some variation in the spelling of 'Gebruikersnaam' and 'Wachtwoord'.

**Comment by robbertkl** [comment]
Unfortunately, I can't get it to work easily. The 'sessies' endpoint seems to require a different format, but even when posting JSON like the JavaScript implementation does, I'm still getting rejected (with the same error message you mentioned).

Have to dive into the exact differences with the JavaScript library to see why that one is working, but I don't really have much time for that now. Perhaps on a rainy day :smile: - just wanted to check if you're aware of this issue. It stopped working out of the blue, so the same might happen for other schools as well.

**Comment by nielskramerr** [comment]
I can confirm this issue, we experience this with multiple schools aswell, and are trying to contact magister directly to ask them if they changed anything in their calls.

**Comment by Stanvk** [comment]
@nielskramerr, could you keep us up-to-date? We will try a few things ourselves as well.

**Comment by Stanvk** [comment]
Schoolmaster internally updated Magister for several schools to version 1.24.40016.9. In this new version the authentication URL is changed which probably causes the problem. I will keep you updated.

**Comment by Stanvk** [comment]
@robbertkl, @nielskramerr Schoolmaster internally updated Magister to version 6.0.24 for several schools. In this new version the authentication URL has been changed. I adjusted it within the master branch. Which is not compatible with version 6.0.23 anymore. The master branch is not fully compatible with version 1.24.40016.9 (6.0.24) yet.
The newest version of the API will be released as soon as possible. This version of the API will, if needed, support both 6.0.23 and 6.0.24.

**Comment by robbertkl** [comment]
Awesome, thanks!

**Comment by nielskramerr** [comment]
Thanks! Working great :) :+1:

**Comment by Stanvk** [comment]
@nielskramerr @robbertkl Do you think support for version 6.0.23 is still necessary? It seems a lot of schools adopted Magister 6.0.24.

**Comment by robbertkl** [comment]
Probably support for the old version can be dropped. If you want to make a more well-informed decision, do a quick (scripted) test like this:
- Get as much schools you can find using https://mijn.magister.net/api/schools?filter= (use common words like _college_, _lyceum_ and _school_ as filter to get a large number) and combine the results.
- Check the Magister version for each of them.

Then make a decision based on the 6.0.24 adoption rate among these schools.

**Comment by ben221199** [comment]
Use https://mijn.magister.net/api/schools?filter=%%% for all results.
