### ISSUE TITLE
Recieving data from parent's account.

### ISSUE THREAD

**Issue by xnfcre** [Stanvk/Magister#16]
Hello,

I have noticed that on some schools using Magister, they only provide an account for the parents. The students see their time table on their parent's account. I've tried getting data when logging in as a parent, but without much success. You are able to get some information, but not for example your homework. I guess it has something to do with being able to have multiple students on the same school, all linked to the parent's account. Do I need to do something different to get things like homework  assignments from a parent's account or is it just not possible?
- Kasper

**Comment by Kickwood** [comment]
It's definitely possible. You would need to create a custom model and get the associated url from the magister.net api. We could do this ourselves but you would have to wait for the next release, which also brings support for the next Magister version and adds a bunch more models.

Something like this would do the trick:

``` php
<?php

namespace Foo\Bar\Parents;

use Config;
use Magister\Services\Database\Elegant\Model;

/**
 * Class Appointment.
 */
class Appointment extends Model
{
    /**
     * Get the url associated with the model.
     *
     * @return string
     */
    public function getUrl()
    {
        return Config::get('url.parents.appointment');
    }
}
```

And then add this to the url.php configuration file:

``` php
'parents' => [
    'appointment' => 'foo/bar/schedule/:child'
]
```

And use it like this:

``` php
Foo\Bar\Parents\Appointment::whereChild(1)->get();
```

But this would all depend on the associated url. You can use developer tools while on Magister and check to see which calls are made and get the url like that.

**Comment by xnfcre** [comment]
Hello kickwood,

Thanks for the response. I am not in a hurry, so I think I'll wait. If I wanted to implement it myself, I would have a problem: I do not know what "developer tools" in magister is or how to access it. I am a student abd I don't think that any admin on our school will lend me their account ;)

The api works like a charm and I am looking forward to the next release.
- Kasper
