### ISSUE TITLE
New dictionary breaks id property

### ISSUE THREAD

**Issue by robbertkl** [Stanvk/Magister#19]
Just ran into an issue with the latest master. Tracked it down to the dictionary.php:
- 8894ee6 was still working OK
- b857248 is (syntactically) broken, it happens :hankey: 
- a73c775 (and later) breaks getting the id property of a `Magister\Models\Course` (and possibly other models as well)

I've made a small test script to illustrate the differences:

``` php
<?php

require(__DIR__ . '/vendor/autoload.php');

$magister = new Magister\Magister('...', '...', ...');
$course = Magister\Models\Course::first();

$tests = [
    'var_dump($course->getKeyName());',
    'var_dump($course->getKey());',
    'var_dump($course->id);',
    'var_dump($course->Id);',
    'var_dump($course["id"]);',
    'var_dump($course["Id"]);',
    'var_dump($course->ToArray()["id"]);',
    'var_dump($course->afkorting);',
];

foreach ($tests as $test) {
    echo "{$test}\n  ";
    eval($test);
}
```

Up until 8894ee6, this resulted in:

```
var_dump($course->getKeyName());
  string(2) "Id"
var_dump($course->getKey());
  NULL
var_dump($course->id);
  int(1422343)
var_dump($course->Id);
  NULL
var_dump($course["id"]);
  int(1422343)
var_dump($course["Id"]);
  NULL
var_dump($course->ToArray()["id"]);
  int(1422343)
var_dump($course->afkorting);
  string(5) "AdAth"
```

It looks like there was already an issue with `#getKey()` using `Id` as a key name, instead of `id`, but perhaps this was affecting `Magister\Models\Course` only. But at least getting the ID using `->id` worked.

In a73c775 and later, this no longer works:

```
var_dump($course->getKeyName());
  string(2) "Id"
var_dump($course->getKey());
  NULL
var_dump($course->id);
  NULL
var_dump($course->Id);
  NULL
var_dump($course["id"]);
  NULL
var_dump($course["Id"]);
  NULL
var_dump($course->ToArray()["id"]);
  int(1422343)
var_dump($course->afkorting);
  string(5) "AdAth"
```

As you can see, the only way of getting the id property was by using `#ToArray()`. Other properties (like `afkorting`) are still working properly.

**Comment by Kickwood** [comment]
Thanks for notifying us. The translator is still a little bit rough and needs some work to be done. We'll release the new version, compatible with the latest Magister version, in a couple of days and make sure everything, including the translator, works adequately.

**Comment by Stanvk** [comment]
@robbertkl I tried to figure it out. It seems Magister itself is inconsistent with their JSON key names. In the specific case of the Course model, the primary key is 'id', not 'Id'.
Magister used to call it 'Id' within version 6.0.23, however they probably changed it to 'id' within the update to version 6.0.24.
