### ISSUE TITLE
Cooldown in Magister ;( (6.0.26)

### ISSUE THREAD

**Issue by xnfcre** [Stanvk/Magister#21]
Hello again,
Magister version 6.0.26 seems to have implemented a cooldown period before you area able to request information again. Are there any work arounds known?
- Kasper

**Comment by Stanvk** [comment]
Thanks for notifying us. We have not maintained Magister lately. We will take a look at it soon and see what we can do.

**Comment by xnfcre** [comment]
It probably doesn't matter anyway, the cooldown is not that long and you should be fine (in most cases) with logging in once.
