### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ghost** [Stanvk/Magister#23]
Als ik een instantie aanmaak en die open met http://localhost:8080/ krijg ik de foutmelding na het openen van het php bestand:

`
'Fatal error: Uncaught exception 'GuzzleHttp\Ring\Exception\ConnectException' with message 'cURL error 6: See http://curl.haxx.se/libcurl/c/libcurl-errors.html' in E:\Profielwerkstuk - kopie\vendor\guzzlehttp\ringphp\src\Client\CurlFactory.php:126 Stack trace: #0 E:\Profielwerkstuk - kopie\vendor\guzzlehttp\ringphp\src\Client\CurlFactory.php(91): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Object(GuzzleHttp\Ring\Client\CurlMultiHandler), Array, Array) #1 E:\Profielwerkstuk - kopie\vendor\guzzlehttp\ringphp\src\Client\CurlMultiHandler.php(244): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Object(GuzzleHttp\Ring\Client\CurlMultiHandler), Array, Array, Array, Resource id #120) #2 E:\Profielwerkstuk - kopie\vendor\guzzlehttp\ringphp\src\Client\CurlMultiHandler.php(136): GuzzleHttp\Ring\Client\CurlMultiHandler->processMessages() #3 E:\Profielwerkstuk - kopie\vendor\guzzlehttp\ringphp\src\Future\BaseFutureTrait.php(118): GuzzleHttp\Ring\Client\CurlMultiHandler->execute() #4 E:\Profielwerkstuk - kopie\vendor\guz in E:\Profielwerkstuk - kopie\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 49'`

**Comment by nielskramerr** [comment]
Als je de link in je foutmelding volgt, en kijkt naar error 6 staat er : 

> CURLE_COULDNT_RESOLVE_HOST (6)
> Couldn't resolve host. The given remote host was not resolved.

Denk dat je dus een fout hebt gemaakt in je configuratie

**Comment by Kickwood** [comment]
Ik kan de error nabootsen door een verkeerd domein in te vullen. Zal dus hieraan liggen, zoals Niels zegt.
