### ISSUE TITLE
Nieuwe veranderingen aan de Magister API

### ISSUE THREAD

**Issue by jbehrens94** [Stanvk/Magister#25]
In mijn REST API tooltje zie ik dat ik geen informatie meer mag opvragen van Magister. Ik krijg bijvoorbeeld op het pad `api/leerlingen/{nummertje}` nu de response `OnvoldoendePrivileges` met omschrijving `null`.
Op `api/accounts/{id}` krijg ik nu `softtokenStatus = 'nietGekoppeld'`. Klinkt mij in de oren als een OAuth systeempje wat ze nu implementeren? De school waar ik mee test gebruikt Magister v6.0.27.

**Comment by Kickwood** [comment]
De resultaten die je krijgt zijn verder gewoon normaal. Lukt het wel om dingen zoals cijfers op te halen?
