### ISSUE TITLE
Stand van zaken

### ISSUE THREAD

**Issue by Stanvk** [Stanvk/Magister#27]
Door gebrek aan tijd werken wij momenteel niet veel aan de API. In de nabije toekomst zijn we van plan om dit weer op te pakken. In de tussentijd houden we een oogje in het zeil en zullen we updates uitvoeren indien noodzakelijk.

Wat de website betreft, deze zal binnenkort weer online komen. De documentatie heeft een zeer hoge prioriteit en zal tegen die tijd grondig onder handen genomen worden. 

Voor vragen en suggesties zijn Christopher (KickWood) en ik altijd bereikbaar.

**Comment by poespas** [comment]
Nice! Succes!!

**Comment by CasperBr** [comment]
Dank voor de update naar 6.1. Het gaf al problemen!

**Comment by Kickwood** [comment]
Als er verder nog problemen zijn door de update horen we het graag :).
