### ISSUE TITLE
Uncaught exception 'CurlException' on new Magister

### ISSUE THREAD

**Issue by boltgolt** [Stanvk/Magister#3]
I'm getting a `Uncaught exception 'CurlException'` error when ever I try to use the `$magister = new Magister('school', 'username', 'password');` line. (with the correct credentials, of course) It seems to try to resolve locations.login as a domain name. Am I missing something here?

```
PHP Fatal error:  Uncaught exception 'CurlException' with message 'CURLE_COULDNT_RESOLVE_HOST: Could not resolve host: locations.login' in  [...]/vendor/shuber/curl/lib/curl.php:169

Stack trace:

#0 [...]/vendor/shuber/curl/lib/curl.php(133): Curl->request('POST', 'locations.login', Array, NULL)

#1 [...]/vendor/stanvk/magister/src/Magister/Magister.php(127): Curl->post('locations.login', Array)

#2 [...]/vendor/stanvk/magister/src/Magister/Magister.php(107): Magister\Magister->invoke('', '')

#3 [...]/vendor/stanvk/magister/src/Magister/Magister.php(51): Magister\Magister->login('', '')

#4 [...]/index.php(8): Magister\Magister->__construct('ozhw', '[leerlingnummer]', '[wachtwoord]')

#5 {main}

  thrown in  [...]/vendor/shuber/curl/lib/curl.php on line 169
```

**Comment by Stanvk** [comment]
Sorry for the inconvenience. Currently, we are working on a new version, which will be released within a few days. We highly recommend you to wait for this new version as the current version is unstable. We are aware of this bug and it will be solved in the new version. To monitor our progress, take a look at the 'dev' branch. Thank you in advance.
