### ISSUE TITLE
Geen manier om de API te gebruiken zonder terminal?

### ISSUE THREAD

**Issue by splintersuidman** [Stanvk/Magister#31]
Ik wil graag de Magister API gebruiken, maar mijn webhosting ondersteunt alleen (S)FTP, en geen terminal. Is er een manier waarop ik de API toch kan gebruiken?

**Comment by Kickwood** [comment]
Je kunt gewoon alles lokaal installeren via Git en Composer en vervolgens uploaden.

**Comment by splintersuidman** [comment]
Oké dankjewel!
