### ISSUE TITLE
Documentation website down

### ISSUE THREAD

**Issue by HoldYourWaffle** [Stanvk/Magister#33]
The [documentation website](http://www.magister-api.nl/) seems to be down.
I just get "Apache is functioning normally" or a 404

**Comment by Kickwood** [comment]
We're working on it.

**Comment by githubuser441** [comment]
Why don't you host it on github it's way more reliable and people can contribute to it.

**Comment by Kickwood** [comment]
https://github.com/magister-api/docs

That's a work in progress, we just haven't had the time for it.

**Comment by p3pijn** [comment]
When will we be able to read the API documentation?

**Comment by Kickwood** [comment]
I'm hoping the website will be fixed within a few days.

As for the documentation itself (the current docs are fairly limited), due to it being a lot of work and me having to do it alone, I hope somewhere before the end of the month.

**Comment by HoldYourWaffle** [comment]
So any updates on the docs?

**Comment by Kickwood** [comment]
Unfortunately I'm unable to reach Stan as he's extremely busy with his study. I don't really have an alternative for the website right now, nor for the documentation itself. Just like Stan I don't have much time to work on the Magister API, merely occasional compatibility updates or quick fixes, let alone work on the new version and finish the documentation. I really do want to finish this but I simply don't have time.

I don't know if someone else is willing to lend a hand with the documentation, me and Stan would certainly appreciate it though.
