### ISSUE TITLE
[IngevoerdDoor] en [Omschrijving] komen niet mee

### ISSUE THREAD

**Issue by joep-nl** [Stanvk/Magister#4]
Klopt het dat [IngevoerdDoor] en [Omschrijving] niet meekomen?

Groet,
Joep

**Comment by Kickwood** [comment]
Naar ik weet worden deze gewoon meegeleverd via de Magister server. Wel zijn deze standaard 'null', mits deze velden daadwerkelijk zijn opgegeven door de invoerder van het desbetreffende cijfer. Je zou eventueel de volgende code kunnen uitvoeren om te controleren welke data wordt meegestuurd door de Magister server:

``` php
var_dump($magister->grades()->first());
```

'KolomOmschrijving' is te vinden onder 'CijferKolom' en 'IngevoerdDoor' staat in de hoofd array.

Ik adviseer je om te wachten op de nieuwe versie van de Magister API, aangezien de huidige vrijgegeven versie soms niet naar behoren werkt. We verwachten hem deze week af te hebben en zal veel meer functionaliteiten bevatten en beter werken dan de huidige versie.

Met vriendelijke groeten,

KickWood
