### ISSUE TITLE
magister-api C#

### ISSUE THREAD

**Issue by LordBunny** [Stanvk/Magister#43]
Ik zou graag magister-api C# lib willen maken maar ik heb een probleem, als ik probeer inteloggen krijg ik dit: 
![loginapi](https://cloud.githubusercontent.com/assets/20775355/23341642/a8ec7592-fc4b-11e6-9d5d-5c770fdfc3e0.PNG)

En de login gegevens zijn correct, en de enige header die ik gebruik is: "application/json"
Wat is precies het gene wat ik verkeerd doe?

**Comment by Kickwood** [comment]
Deze error wordt alleen gegeven als de inloggegevens niet correct zijn. Het kan dus niet anders dan dat jij hier ergens een fout in hebt gemaakt. Probeer stapsgewijs alles te controleren en vergeet niet te letten op data types.

**Comment by LordBunny** [comment]
Ik weet wat het probleem is, de cookie. Nu ik dat weet zou ik willen weten hoe ik de SESSION_ID= krijg. Heb jij een idee hoe ik die moet krijgen?

**Comment by Kickwood** [comment]
De endpoint waarnaar jij de inloggegevens post, geeft een set-cookie header terug met daarin de SESSION_ID cookie. Dan is het gewoon een kwestie van de header uitlezen en de cookie verwerken.

**Comment by LordBunny** [comment]
Maar er moet toch ook nog een cookie verzonden worden?

**Comment by Kickwood** [comment]
Dan stuur je gewoon een cookie header mee met elk request dat je maakt naar Magister.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie

**Comment by LordBunny** [comment]
Maar in die Request Cookie header moet toch ook nog een SessionID staan? En hoe krijg ik die dan?

**Comment by Kickwood** [comment]
Ik denk dat je toch echt meer onderzoek moet doen, aangezien je om dingen vraagt die je zou moeten weten. Ik zal het even oppervlakkig proberen uit te leggen, maar liever verwijs ik je door naar het Internet.

1. Eerst moet de gebruiker geauthoriseerd worden door de externe Magister API. Je stuurt hiervoor een request met daarin minstens een gebruikersnaam en wachtwoord. Bij een succesvolle authenticatie stuurt de API een response met daarin een Set-Cookie header. Normaliter gebruikt de browser dit om lokaal een cookie aan te maken, die vervolgens bij elk request wordt meegestuurd. Dit zouden wij dus moeten nabootsen. Dmv je code lees je de cookies uit die Magister terugstuurt - in dit geval één cookie met de naam SESSION_ID. De waarde van deze cookie sla je lokaal op.

2. Bij alle daaropvolgende requests naar een API endpoint waarvoor we ingelogd moeten zijn, moeten wij nu precies dezelfde cookie opsturen. Magister gebruikt dit dan intern om te controleren of de gebruiker is ingelogd. Dit doen wij nu dmv een Cookie header. Hierin moet een cookie gedefinieerd worden met de naam SESSION_ID met de waarde die we eerder lokaal opgeslagen hebben. Wij sturen dus eigenlijk de cookie gedefineerd in de Set-Cookie header terug in een Cookie header. De naam en waarde van de cookie  moeten overeenkomen.

Overigens weet ik niet of jij doorhebt dat wij niet van Magister zelf zijn, maar dit enkel een PHP library is voor Magister die wij hebben gepubliceerd.

**Comment by LordBunny** [comment]
Ik bedoel dat er in de request header al een SESSION_ID staat en ik die in mijn code niet kan Posten.
![dit](https://cloud.githubusercontent.com/assets/20775355/23408842/c9d67d14-fdc9-11e6-879b-d9a24aab498c.PNG)

De Response Headers die ik krijg op de site zijn:

![dit2](https://cloud.githubusercontent.com/assets/20775355/23409064/870568dc-fdca-11e6-89fa-53bddcf07ce1.PNG)

En de Reponse Headers in mijn code: 
![dit3](https://cloud.githubusercontent.com/assets/20775355/23409115/b0b93ad2-fdca-11e6-9482-54e9ebd83740.PNG)

En de Request Header in mijn code:
Accept: application/json

**Comment by Kickwood** [comment]
Ik denk dat ik je probleem eindelijk begrijp. Voordat je probeert in te loggen moet je eerst een DELETE request versturen naar `/api/sessies/huidige`. Deze geeft een Set-Cookie header terug, waarvan de cookie vervolgens dient meegegeven te worden met je login request. Als je dit eerst doet en vervolgens probeert in te loggen zou je Bad Request moeten verdwijnen en de Magister API een Set-Cookie header moeten teruggeven.

**Comment by LordBunny** [comment]
Ik denk dat dat ^^ Erg helpt bedankt

**Comment by LordBunny** [comment]
Het werkt nu, bedankt
