### ISSUE TITLE
Magister update?

### ISSUE THREAD

**Issue by nielskramerr** [Stanvk/Magister#44]
Er lijkt wederom een nieuwe magister update plaats te hebben gevonden, namelijk die naar 6.1.11...

Ook deze update lijkt  ervoor gezorgt te hebben dat de API niet meer werkt, ik zal vanavond even dieper in de code duiken of ik kan vinden waarom...

Persoonlijk krijg ik bij elke school die via mijn applicatie aangesloten is de "cURL error 6: Could not resolve host:" error..
( Er was sinds gister al een probleem, toen was de error wel nog anders! Toen kreeg ik een error op een array_key_exists functie waarbij ergens een tweede argument geen array meer was maar een string...) 

Graag hoor ik of andere mensen ook dit probleem hebben en of iemand misschien op basis van deze errors gelijk een oplossing weet!

**Comment by nielskramerr** [comment]
Lijkt toch met iets buiten Magister te maken te hebben... Close voor nu dit issue..

**Comment by nielskramerr** [comment]
Na wat onderzoek kwam de cURL error door een ubuntu service update...
Wel ben ik weer terug bij de array_key_exists error.

De hele error in de log is als volgt: 
`Magister error ["[object] (ErrorException(code: 0): array_key_exists() expects parameter 2 to be array, string given at /var/www/vendor/laravel/framework/src/Illuminate/Support/Arr.php:241)"] []`

Na een dump in dit bestand om te kijken wat er dan opgestuurd wordt, krijg ik het volgende te zien
```
De functie:

public static function has($array, $key)

$array => "Invalid API key"
$key => "Items"
```

Dit is dus sinds zeer recent en zou eventueel met een update te maken kunnen hebben ? 
Hebben jullie een idee wat deze error kan veroorzaken?

**Comment by Kickwood** [comment]
Dit komt omdat de API key niet mee wordt gestuurd met Magister. Dit is opgelost in een update, dus ik denk dat je Magister versie verouderd is.

Ik heb toen deze regels toegevoegd aan `Magister\Services\Http\HttpServiceProvider`:

```php
$client->setDefaultOption('headers', [
    'X-API-Client-ID' => env('MAGISTER_API_KEY', '12D8'),
]);
```

Ik denk dat ze met de nieuwe update deze header nu verplicht hebben gemaakt.

**Comment by Kickwood** [comment]
Overigens zijn deze errors van Magister heel moeilijk te verwerken omdat al hun errors een ander formaat hebben. Ik had het graag anders gezien, want dan zouden dit soort problemen niet voorkomen en zou het meteen duidelijk zijn waar het probleem ligt.

**Comment by nielskramerr** [comment]
Excuus.. had inderdaad met een outdated versie te maken.. Sorry voor het ongemak.
