### ISSUE TITLE
Paar vragen

### ISSUE THREAD

**Issue by khawtf** [Stanvk/Magister#45]
Ik vroeg mij af de API alleen werkt voor leerlingen of ook voor docenten.
Voor welke versie van magister is dit ? 
Kan ik met deze api bijvoorbeeld alle berichten van "Vandaag"  ophalen of alle absenties/te laat van leerlingen opvragen ?

Thanks en keep up the good work  ;)

**Comment by jonkootje** [comment]
Ohoh deze dude wilt kinderen automatisch laten nablijven ofzo :san_marino:

**Comment by jonkootje** [comment]
Ohoh deze dude wilt kinderen automatisch laten nablijven ofzo :S

**Comment by khawtf** [comment]
Hehe ik wil rapportages maken met third party libraries. Maar ik zie nog niet zo snel wat wel of niet kan en hoe de modellen precies werken

**Comment by Kickwood** [comment]
Je kunt in principe alle gegevens ophalen die je zelf als leerling kunt zien op de Magister website van jouw school. Enkel ontbreekt nog support voor het aanmaken of verwijderen van externe data (denk aan e-mails versturen). Dit is nog WIP en zal pas in de volgende versie komen.

Wat betreft de docenten: ik geloof dat zij nog de oude versie van Magister gebruiken (Silverlight). Wij bieden enkel ondersteuning voor de nieuwe Magister versie die tot dusver alleen nog toegankelijk is voor leerlingen. Mochten de docenten overschakelen naar Magister 6, dan zal hier uiteraard ook ondersteuning voor komen.

Samengevat kun je inderdaad de berichten van vandaag ophalen en alle absenties/te laat van leerlingen opvragen.

Overigens ben ik gisteren begonnen aan de nieuwe documentatie. Link staat in de readme.md.

**Comment by khawtf** [comment]
thanks voor de antwoorden. Inderdaad de magister met alle functionaliteiten van docenten is dat ene rommel product met silverlight 🗡 .

Ik kan wel inloggen op magister 6 met een docenten account en ik zie wel het een en ander maar niet alle functionaliteiten natuurlijk.
Ik moet even begrijpen hoe je de modellen maakt want ik zie nu niet even snel hoe je dus absenties/te laat ophaalt.

**Comment by Kickwood** [comment]
Wil je de absenties/te laat ophalen van docenten of van leerlingen?

**Comment by khawtf** [comment]
Van leerlingen...

**Comment by Kickwood** [comment]
Ok, je bracht mij even in verwarring door docenten erbij te betrekken.

Elk model staat gelijk aan één extern endpoint van Magister. Het fungeert dus als een soort brug. Hierbij worden handige functies meegeleverd die het ophalen en verwerken van de data vereenvoudigden.

Voor het ophalen van absenties ed. werken we met het Attendence model. Deze staat gelijk aan het externe endpoint `personen/:id/absenties?van=:from&tot=:until`. Alle modellen fungeren als een soort query builder. De `:from` en `:until` kunnen we dynamisch invullen met de `where()` functie.

```php
use Magister\Models\Attendance\Attendance;

$attendances = Attendance::where('from', '2017-01-01')->where('until', '2017-02-01')->get();
```

De Magister website doet hier precies hetzelfde. In de front-end filteren zij vervolgens de verschillende typen absenties eruit (absent, te laat, ziek etc.). De `get()` functie verstuurt het daadwerkelijke request naar zijn Magister endpoint en slaat de data op in een `Collection` class. Dit is een class met een aantal handige functies voor het verder verwerken van de data. Zie https://github.com/magister-api/magister/blob/master/src/Magister/Services/Support/Collection.php voor alle functies beschikbaar.

Als we nu enkel de te laat op willen halen kunnen we de `where()` functie van de `Collection` class gebruiken.

```php
use Magister\Models\Attendance\Attendance;

$attendances = Attendance::where('from', '2017-01-01')->where('until', '2017-02-01')->get();
$toolate = $attendances->where('Code', 'TL');

// Als we ze vervolgens willen tellen
$quantity = $toolate->count();
```

Hier komt binnenkort meer over in de documentatie.

**Comment by khawtf** [comment]
new Magister\Magister("XXX","XXX","XXX");
use Magister\Models\Attendance\Attendance;

$attendances = Attendance::where('from', '2017-01-01')->where('until', '2017-02-01')->get();
$toolate = $attendances->where('Code', 'TL');


var_dump($toolate);

dit is het resultaat:

Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/magister/vendor/stanvk/magister/src/Magister/Services/Foundation/Bootstrap/MakeReplacements.php on line 29
object(Magister\Services\Support\Collection)#2 (1) { ["items":protected]=> array(0) { } }

**Comment by Kickwood** [comment]
Deze error heeft te maken met het inlog proces.

Kun je even het resultaat doorsturen van:

```php
var_dump(Magister\Models\User::profile());
```

Bij een error gelieve de hele stack trace.

**Comment by khawtf** [comment]
Notice: Trying to get property of non - object in /Applications/MAMP / htdocs / magister / vendor / stanvk / magister / src / Magister / Services / Foundation / Bootstrap / MakeReplacements.php on line 29
object(Magister\ Models\ User) #58 (5) { ["primaryKey":protected]= > string(10)
"Persoon.Id" ["dates": protected] => array(1) {
	[0] => string(13)
	"Geboortedatum"
}["connection": protected] => NULL["attributes": protected] => array(4) {
	["UuId"] => string(36)
	"XXXXX" ["Persoon"] => array(12) {
		["Id"] => int(xxxx)["Roepnaam"] => string(6)
		"XXXXX" ["Tussenvoegsel"] => NULL["Achternaam"] => string(12)
		"XXXXX" ["OfficieleVoornamen"] => string(6)
		"XXXX" ["Voorletters"] => string(2)
		"X." ["OfficieleTussenvoegsels"] => NULL["OfficieleAchternaam"] => NULL["Geboortedatum"] => string(10)
		"XXXXX" ["GeboorteAchternaam"] => NULL["GeboortenaamTussenvoegsel"] => NULL["GebruikGeboortenaam"] => bool(false)
	}["Groep"] => array(2) {
		[0] => array(3) {
			["Naam"] => string(6)
			"Docent" ["Privileges"] => array(51) {
				[0] => array(2) {
					["Naam"] => string(12)
					"Aanmeldingen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[1] => array(2) {
					["Naam"] => string(18)
					"WachtwoordWijzigen" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[2] => array(2) {
					["Naam"] => string(11)
					"EloOpdracht" ["AccessType"] => array(2) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read"
					}
				}[3] => array(2) {
					["Naam"] => string(13)
					"Studiewijzers" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[4] => array(2) {
					["Naam"] => string(7)
					"Bronnen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[5] => array(2) {
					["Naam"] => string(9)
					"Berichten" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[6] => array(2) {
					["Naam"] => string(7)
					"Profiel" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[7] => array(2) {
					["Naam"] => string(9)
					"Absenties" ["AccessType"] => array(3) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Delete"
					}
				}[8] => array(2) {
					["Naam"] => string(9)
					"Afspraken" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[9] => array(2) {
					["Naam"] => string(18)
					"Roosterwijzigingen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[10] => array(2) {
					["Naam"] => string(12)
					"Instellingen" ["AccessType"] => array(3) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Delete"
					}
				}[11] => array(2) {
					["Naam"] => string(13)
					"Keuzewerktijd" ["AccessType"] => array(3) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Delete"
					}
				}[12] => array(2) {
					["Naam"] => string(10)
					"Ouderavond" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[13] => array(2) {
					["Naam"] => string(9)
					"Logboeken" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[14] => array(2) {
					["Naam"] => string(6)
					"Lessen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[15] => array(2) {
					["Naam"] => string(11)
					"Lesperioden" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[16] => array(2) {
					["Naam"] => string(11)
					"Medewerkers" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[17] => array(2) {
					["Naam"] => string(16)
					"LeerlingenOuders" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[18] => array(2) {
					["Naam"] => string(16)
					"Persoonsgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[19] => array(2) {
					["Naam"] => string(36)
					"MedewerkersOfficielePersoonsgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[20] => array(2) {
					["Naam"] => string(27)
					"LOOfficielePersoonsgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[21] => array(2) {
					["Naam"] => string(17)
					"LOContactgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[22] => array(2) {
					["Naam"] => string(15)
					"LOAdresgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[23] => array(2) {
					["Naam"] => string(16)
					"Examenresultaten" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[24] => array(2) {
					["Naam"] => string(19)
					"Terugkommaatregelen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[25] => array(2) {
					["Naam"] => string(5)
					"Taken" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[26] => array(2) {
					["Naam"] => string(7)
					"Studies" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[27] => array(2) {
					["Naam"] => string(15)
					"VerantwoordeLes" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[28] => array(2) {
					["Naam"] => string(10)
					"Leerlingen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[29] => array(2) {
					["Naam"] => string(6)
					"Ouders" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[30] => array(2) {
					["Naam"] => string(12)
					"Leerling-NAW" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[31] => array(2) {
					["Naam"] => string(17)
					"Leerling-huisarts" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[32] => array(2) {
					["Naam"] => string(28)
					"Leerling-medische-informatie" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[33] => array(2) {
					["Naam"] => string(10)
					"Ouders-NAW" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[34] => array(2) {
					["Naam"] => string(14)
					"Medewerker-NAW" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[35] => array(2) {
					["Naam"] => string(20)
					"Medewerker-NAW-prive" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[36] => array(2) {
					["Naam"] => string(17)
					"Leerling-mentoren" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[37] => array(2) {
					["Naam"] => string(11)
					"Persoonlijk" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[38] => array(2) {
					["Naam"] => string(7)
					"Gedeeld" ["AccessType"] => array(2) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read"
					}
				}[39] => array(2) {
					["Naam"] => string(10)
					"Prullenbak" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[40] => array(2) {
					["Naam"] => string(6)
					"Vakken" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[41] => array(2) {
					["Naam"] => string(12)
					"Cijferinvoer" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[42] => array(2) {
					["Naam"] => string(20)
					"ExamenAfnamemomenten" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[43] => array(2) {
					["Naam"] => string(15)
					"Docentlicenties" ["AccessType"] => array(3) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Delete"
					}
				}[44] => array(2) {
					["Naam"] => string(11)
					"ToetsGemist" ["AccessType"] => array(2) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read"
					}
				}[45] => array(2) {
					["Naam"] => string(19)
					"Leerling-resultaten" ["AccessType"] => array(1) {
						[0] => string(4)
						"None"
					}
				}[46] => array(2) {
					["Naam"] => string(7)
					"Groepen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[47] => array(2) {
					["Naam"] => string(9)
					"Profielen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[48] => array(2) {
					["Naam"] => string(8)
					"ILTCodes" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[49] => array(2) {
					["Naam"] => string(24)
					"BeschikbaareidOuderavond" ["AccessType"] => array(2) {
						[0] => string(4)
						"Read" [1] => string(6)
						"Update"
					}
				}[50] => array(2) {
					["Naam"] => string(12)
					"Mededelingen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}
			}["Links"] => NULL
		}[1] => array(3) {
			["Naam"] => string(10)
			"Klasdocent" ["Privileges"] => array(44) {
				[0] => array(2) {
					["Naam"] => string(12)
					"Aanmeldingen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[1] => array(2) {
					["Naam"] => string(11)
					"EloOpdracht" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[2] => array(2) {
					["Naam"] => string(13)
					"Studiewijzers" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[3] => array(2) {
					["Naam"] => string(7)
					"Bronnen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[4] => array(2) {
					["Naam"] => string(9)
					"Berichten" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[5] => array(2) {
					["Naam"] => string(7)
					"Profiel" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[6] => array(2) {
					["Naam"] => string(9)
					"Absenties" ["AccessType"] => array(3) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Delete"
					}
				}[7] => array(2) {
					["Naam"] => string(9)
					"Afspraken" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[8] => array(2) {
					["Naam"] => string(18)
					"Roosterwijzigingen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[9] => array(2) {
					["Naam"] => string(12)
					"Instellingen" ["AccessType"] => array(3) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Delete"
					}
				}[10] => array(2) {
					["Naam"] => string(13)
					"Keuzewerktijd" ["AccessType"] => array(3) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Delete"
					}
				}[11] => array(2) {
					["Naam"] => string(10)
					"Ouderavond" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[12] => array(2) {
					["Naam"] => string(9)
					"Logboeken" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[13] => array(2) {
					["Naam"] => string(6)
					"Lessen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[14] => array(2) {
					["Naam"] => string(11)
					"Lesperioden" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[15] => array(2) {
					["Naam"] => string(11)
					"Medewerkers" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[16] => array(2) {
					["Naam"] => string(16)
					"LeerlingenOuders" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[17] => array(2) {
					["Naam"] => string(16)
					"Persoonsgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[18] => array(2) {
					["Naam"] => string(36)
					"MedewerkersOfficielePersoonsgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[19] => array(2) {
					["Naam"] => string(27)
					"LOOfficielePersoonsgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[20] => array(2) {
					["Naam"] => string(17)
					"LOContactgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[21] => array(2) {
					["Naam"] => string(15)
					"LOAdresgegevens" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[22] => array(2) {
					["Naam"] => string(16)
					"Examenresultaten" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[23] => array(2) {
					["Naam"] => string(19)
					"Terugkommaatregelen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[24] => array(2) {
					["Naam"] => string(5)
					"Taken" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[25] => array(2) {
					["Naam"] => string(7)
					"Studies" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[26] => array(2) {
					["Naam"] => string(15)
					"VerantwoordeLes" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[27] => array(2) {
					["Naam"] => string(10)
					"Leerlingen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[28] => array(2) {
					["Naam"] => string(6)
					"Ouders" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[29] => array(2) {
					["Naam"] => string(12)
					"Leerling-NAW" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[30] => array(2) {
					["Naam"] => string(17)
					"Leerling-huisarts" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[31] => array(2) {
					["Naam"] => string(10)
					"Ouders-NAW" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[32] => array(2) {
					["Naam"] => string(14)
					"Medewerker-NAW" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[33] => array(2) {
					["Naam"] => string(11)
					"Persoonlijk" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[34] => array(2) {
					["Naam"] => string(7)
					"Gedeeld" ["AccessType"] => array(2) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read"
					}
				}[35] => array(2) {
					["Naam"] => string(10)
					"Prullenbak" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[36] => array(2) {
					["Naam"] => string(6)
					"Vakken" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[37] => array(2) {
					["Naam"] => string(20)
					"ExamenAfnamemomenten" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[38] => array(2) {
					["Naam"] => string(15)
					"Docentlicenties" ["AccessType"] => array(4) {
						[0] => string(6)
						"Create" [1] => string(4)
						"Read" [2] => string(6)
						"Update" [3] => string(6)
						"Delete"
					}
				}[39] => array(2) {
					["Naam"] => string(11)
					"ToetsGemist" ["AccessType"] => array(1) {
						[0] => string(4)
						"None"
					}
				}[40] => array(2) {
					["Naam"] => string(7)
					"Groepen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[41] => array(2) {
					["Naam"] => string(9)
					"Profielen" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[42] => array(2) {
					["Naam"] => string(8)
					"ILTCodes" ["AccessType"] => array(1) {
						[0] => string(4)
						"Read"
					}
				}[43] => array(2) {
					["Naam"] => string(24)
					"BeschikbaareidOuderavond" ["AccessType"] => array(1) {
						[0] => string(4)
						"None"
					}
				}
			}["Links"] => NULL
		}
	}["Links"] => array(0) {}
}["relations": protected] => array(0) {}
}

**Comment by Kickwood** [comment]
Stuur me anders maar even een berichtje op Gitter.

**Comment by Kickwood** [comment]
Momenteel even druk dus ik kom nog er op terug. Lijkt op een probleem specifiek aan jou.
