### ISSUE TITLE
:S Ehhm een ssl certificate?

### ISSUE THREAD

**Issue by jonkootje** [Stanvk/Magister#47]
Waarom is dat openssl programma installeren zo'n pain in the ass? Kan iemand me helpen met het maken van een ssl key om de api te gebruiken?

**Comment by Kickwood** [comment]
Ik begrijp het probleem niet echt. Je hebt een probleem met het installeren van de OpenSSL extensie voor PHP? Over welke 'SSL key' gaat dit precies?

**Comment by jonkootje** [comment]
https://i.gyazo.com/8ad9bdc08878ba76011253627cdf9dc9.png <-- op dit voorbeeld op jullie magister documentatie site staat er dat je een $key variable moet geven. Ik neem aan dat dit een ssl key is of is het wat anders?

**Comment by githubuser441** [comment]
> The next thing you should do after installing the Magister 6 API is set your encryption key to a random string.
link: http://magister-6-api.readthedocs.io/en/latest/installation.html#encryption-key

**Comment by jonkootje** [comment]
https://gyazo.com/9b2725c35559cc308e0a80e04245777f <-- What does this mean?

**Comment by Kickwood** [comment]
Probleem heeft niet te maken met Magister maar met je webserver.

Deze error wordt veroorzaakt doordat Magister https gebruikt en jouw locale bundel CA certificaten (cacert.pem) niet up-to-date is of niet bestaat. Je moet in je php.ini kijken of een certificaat geconfigureerd is, en als deze verouderd is of niet bestaat, dan moet je er een downloaden van de cURL website en in je php.ini configureren.

https://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config

**Comment by Kickwood** [comment]
Geen activiteit, dus neem aan dat het opgelost is.
