### ISSUE TITLE
Voorbeeld code

### ISSUE THREAD

**Issue by Qwyrp** [Stanvk/Magister#48]
Mogelijk is dit niet de plek maar ik zoek een beginnetje. Is er ms een voorbeeldstukje code waar wat gegevens worden uitgelezen o.i.d. zodat ik weet wat er allemaal aangeroepen moet worden

**Comment by Kickwood** [comment]
Er staan een paar voorbeelden op Gitter als je even naar boven scrollt.

**Comment by Kickwood** [comment]
Mochten meer voorbeelden nodig zijn of mochten er onduidelijkheden zijn, hoor ik het graag.

De documentatie zal binnenkort weer uitgebreid worden, maar momenteel heb ik even geen tijd.
