### ISSUE TITLE
Weging

### ISSUE THREAD

**Issue by joep-nl** [Stanvk/Magister#5]
Is er een mogelijkheid om de weging van de cijfers mee te krijgen?

Groet,
Joep de Jong

**Comment by Stanvk** [comment]
Doordat de API zo gemakkelijk uit te breiden is kan dit zelf gedaan worden.
Zie de Locations.php in de Config folder. Echter, doordat er nog geen stable build is zal deze functie nog niet werken. 

We zullen het toevoegen met de volgende update!

**Comment by Kickwood** [comment]
Eerst halen we alle cijfers op en lopen hier doorheen, daarna halen we door middel van de `info()` relatie de informatie op over het cijfer:

``` php
use Magister\Models\Grade;

$cijfers = Grade::all();

foreach ($cijfers as $cijfer)
{
    echo $cijfer->info()->Weging;
}
```

Dit en nog veel meer dingen zullen binnenkort ook in de documentatie komen te staan.

**Comment by xnfcre** [comment]
Hmm, het lijkt erop dat Weging niet gedefinieerd is. In $cijfer->info() staat heel veel, maar een weging kan ik niet vinden.
- Kasper

**Comment by robbertkl** [comment]
In bovenstaand voorbeeld zitten volgens mij 2 fouten:
- Het grade model zit in `Magister\Models\Grade\Grade`
- Het moet `->info` zijn in plaats van `->info()`

Het complete wordt dan:

``` php
use Magister\Models\Grade\Grade;

$cijfers = Grade::all();

foreach ($cijfers as $cijfer)
{
    echo $cijfer->info->Weging;
}
```

Dit geeft bij mij de correcte resultaten.

**Comment by xnfcre** [comment]
Je hebt gelijk, bedankt.
- Kasper

**Comment by Stanvk** [comment]
@xnfcre Momenteel is de documentatie niet veels soeps, ik hoop dit bij de release van versie 2.1.0 verbeterd te hebben.

**Comment by Kickwood** [comment]
@robbertkl Voorbeeld was verouderd (zie post datum). Hoe dan ook, je hebt helemaal gelijk.

**Comment by JeroenFlink** [comment]
$cijfers = Grade::all();
werkt voor de huidige periode, dat is fijn.

Hoe vraag ik de cijfers van een ander periode op ?
Bijvoorbeeld PER1 PER2 PER3 of liefst alle perioden ?

**Comment by nielskramerr** [comment]
Voorzover ik gevonden heb is hier geen ondersteuning voor op het moment.

Maar als je toch iets als alle cijfer periodes wilt, kun je de url van Grades in url.php aanpassen.
In mijn situatie had ik ook alle cijferperiodes nodig, en hoefde ik alleen `?actievePerioden=false` achter de url te zetten. Wat dan de volgende url zou opleveren:
`'grade' => 'personen/:id/aanmeldingen/:enrollment/cijfers/cijferoverzichtvooraanmelding?actievePerioden=false',`

Die url kun je zelf eenvoudig achterhalen door bij de school waar je voor bezig bent even de calls na te gaan. Heb namelijk geen idee of deze url voor elke school zal werken.

**Comment by Kickwood** [comment]
Magister zelf haalt gewoon alle periodes op en filtreert op basis van user input welke gegevens getoond dienen te worden. De methode van @nielskramerr is dan ook het handigste, hoewel even wat meer toelichting hierop.

In plaats van url.php te bewerken is het ook mogelijk om parameters aan de url mee te geven via Elegant; onze 'database' engine:

``` php
$grades = Grade::where('actievePerioden', 'false')->get();
```

Dit voegt automatisch `?actievePerioden=false` aan de url toe. Daarnaast kan de naam ook worden opgenomen in de `where()` mocht je daar behoefte aan hebben.

Om maar een voorbeeld te geven:

``` php
$appointments = Appointment::whereVan($foo)->whereTot($bar)->get();
```

Dit zou hetzelfde zijn als:

``` php
$appointments = Appointment::where('van', $foo)->where('tot', $bar)->get();
```

En de url zou dan `personen/:id/afspraken?van=$foo&tot=$bar` worden.

**Comment by JeroenFlink** [comment]
Dankjewel !, het werkt

Ik heb in de source code gekeken en daar komen deze commando's niet voor dus documentatie is echt nodig. Maw het is dusdanig geprogrammeerd dat je er zonder documentatie onmogelijk uit kunt komen.

**Comment by Kickwood** [comment]
De site van de Magister API met enige documentatie daarop is door problemen offline. We zullen zorgen dat deze, inclusief de documentatie, een dezer dagen weer online komt. De documentatie (uitbreiden) is momenteel onze nummer 1 prioriteit.

**Comment by PeterGrid** [comment]
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ParseException' with message 'Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON' in /root/magister/vendor/guzzlehttp/guzzle/src/Message/Response.php:148

Hmmm, is er misschien een makkelijke fix voor deze error die ineens zich voordoet ?

Misschien ergens een functie vervangen van json (en)de-code naar (de)serialize ?
