### ISSUE TITLE
Wordt er nog wat aan dit project gedaan?

### ISSUE THREAD

**Issue by Wqrld** [Stanvk/Magister#50]
wordt deze api nog ondersteund?

**Comment by 7kasper** [comment]
Er zijn wel wat aanpassingen in magister geweest deze vakantie dus het kan zijn dat er iets kapot is. 

> Maar ik heb dat tot zover nog niet gemerkt, ik gebruik nu alleen huiswerk

Ik stel dat er nu niet echt actief aan gewerkt word, maar dat de API (in ieder geval deels) nog wel werkt.
(Zie gitter)

**Comment by Kickwood** [comment]
Ik heb het behoorlijk druk nu en geen tijd om te controleren of de API nog werkt met de nieuwe Magister update. Ik heb gezien dat er opzich weinig is vernaderd muv 2 nieuwe API urls die nu nodig zijn om in te loggen: een POST naar `/gebruikersnaam` en naar `/wachtwoord`. Het zou kunnen dat de Magister API nog werkt, het zou kunnen van niet. Dit zou dan te wijten zijn aan de eerder genoemde veranderingen aan de authenticatie. In wezen is dit super eenvoudig op te lossen, echter heb ik de tijd niet om deze oplossing dus te testen. Daarbij ten overvloede de opmerking dat ik mogelijk binnenkort geen toegang meer heb tot een Magister account.
