### ISSUE TITLE
Agenda data

### ISSUE THREAD

**Issue by ItsMeRomian** [Stanvk/Magister#51]
Magister\Models\Appointment::today() is een array en ik snap dat je met een foreach loop data eruit kan halen.
````php
foreach (Magister\Models\Appointment::today() as $appointment) {
    echo $appointment->Omschrijving;
}
````
Maar nu zie ik dat als ik `var_dump(Magister\Models\Appointment::today())` doe er ook "dieperliggende" data is:
````php
["Vakken"] => array(1) {
                    [0] => array(2) {
                        ["Id"] => int(81) 
                        ["Naam"] => string(22) "Wiskunde" 
                    } 
}
````
Hoe verkrijg ik die data?
Ohja en wanneer komt de verbeterde documentatie uit?

**Comment by Kickwood** [comment]
Dat is verder gewoon basis PHP. Zo te zien is 'Vakken' een array met één waarde waar evt. verscheidene waardes in kunnen voorkomen. Ervan uitgaande dat er sprake is van één waarde (het meest waarschijnlijke, maar je weet maar nooit) kan het op de volgende manieren:

```php
foreach (Magister\Models\Appointment::today() as $appointment) {
  // We slaan de array 'Vakken' op in de variable $subjects.
  $subjects = $appointment->Vakken;

  // We kunnen de waardes direct krijgen dmv. de index (0 in dit geval).
  // http://php.net/manual/en/language.types.array.php
  $subject = $subjects[0];

  // We kunnen ook een PHP functie gebruiken om de eerste waarde te krijgen.
  // http://php.net/manual/en/function.array-shift.php
  $subject = array_shift($subjects);

  // Wat we nu terugkrijgen is een array met twee elementen (nl. met de key 'Id' en 'Naam').
  $subject_id = $subject['Id'];
  $subject_name = $subject['Naam'];

  // Nu zonder tussen variables voor bv. de naam van het vak.
  $subject_name = $appointment->Vakken[0]['Naam'];
}
```

Mochten er meer vakken in een dergelijke array staan, dan zou je weer een foreach moeten doen over de vakken en daarin de noodzakelijke logica om de gegevens te krijgen die je wilt.

Wat betreft de documentatie heb ik overigens totaal geen tijd. Het feit dat ik geen toegang meer heb tot een Magister account helpt daar niet bij. Het zal dus nog wel enige tijd duren voordat de documentatie af is.

**Comment by ItsMeRomian** [comment]
Dankjewel ben nog niet zo lang bezig met php maar nu snap ik het
