### ISSUE TITLE
Magister foto

### ISSUE THREAD

**Issue by ItsMeRomian** [Stanvk/Magister#53]
Hoe verkrijg ik de profielfoto van een magister account? magister.net gebruikt deze link: school.magister.net/api/personen/*MagisterID*/foto
MagisterID is hier `Persoon->Id` in `Magister\Models\User::profile();`

**Comment by Kickwood** [comment]
```php
// header('Content-Type: image/jpeg');

$id = Auth::id();

$picture = Http::get("personen/$id/foto?width=32&height=32&crop=true")->getBody();

// echo $picture;
```

`Auth::id()` hier is hetzelfde als `Magister\Models\User::profile()->Persoon['Id']`, echter is `Auth::id()` een gecachete waarde, wat betekent dat dit sneller is dan laatstgenoemde aangezien dit een oproep naar de Magister server scheelt.

De modellen van de API bieden geen ondersteuning voor afbeeldingen, daarom moet hier gebruikt gemaakt worden van de HTTP provider. Deze provider is een wrapper voor Guzzle met de Magister loginsessie standaard meegegeven. Dit betekent ook dat alle functies van Guzzle gebruikt kunnen worden.

De uitgecommenteerde regels zijn voor als je de afbeelding in de browser wilt tonen.
