### ISSUE TITLE
New magister api

### ISSUE THREAD

**Issue by CasperBr** [Stanvk/Magister#57]
I received a message from magister that there will be a major update. Will you provide support for this or will there be no more development?

**Comment by ItsMeRomian** [comment]
Where have you received this message? Can you show us?

**Comment by Stanvk** [comment]
Unfortunately I do not know what SchoolMaster will change in their newest version of Magister. However, the API is very dynamical and thus features can easily be added or altered.

If there are no radical changes in the newest version, it is very likely that the Magister API will be updated as well.

@CasperBr, do you have any information on this topic?

**Comment by CasperBr** [comment]
Hi there,

I received documents about them disabling all active API keys, after which they will introduce
their new oAuth API. I am not sure if I am allowed to send you the documents. The new API will
be introduced October 22nd.

To be able to use it they informed me that IP-addresses will have to be whitelisted. I guess if you
want to continue to support the API you will have to get in contact with the developers.

Can i help with anything else?

Kind regards,
Casper

Op 4 sep. 2018, om 13:20 heeft Stan van Kraaij <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Unfortunately I do not know what SchoolMaster will change in their newest version of Magister. However, the API is very dynamical and thus new features can easily be added or altered.

@CasperBr<https://github.com/CasperBr>, do you have any information on this topic?
