### ISSUE TITLE
selecting a diferent year for grades

### ISSUE THREAD

**Issue by ItsMeRomian** [Stanvk/Magister#59]
How do you select a diverent year with grades. `Magister\Models\Grade\Grade::all()` just gives me the current year and does not take any arguments.

**Comment by Kickwood** [comment]
Het Grade Model gebruikt de volgende URL:

`personen/:id/aanmeldingen/:enrollment/cijfers/cijferoverzichtvooraanmelding`

De `cijferoverzichtvooraanmeldingen` accepteert de volgende argumenten met de volgende default waarden:

actievePerioden=true
alleenBerekendeKolommen=false
alleenPTAKolommen=false
peildatum=2019-07-31 (de maand en dag zou per school kunnen verschillen, dit weet ik niet)

Volgensmij kun je verschillende jaren krijgen dmv de peildatum aan te passen:

```php
$grades = Magister\Models\Grade\Grade::where('peildatum', '2017-07-31')->get();
```

Dit zou dan de cijfers van jaar 2016-2017 moeten teruggeven.
