### ISSUE TITLE
Composer fails to install

### ISSUE THREAD

**Issue by JoeyHoutenbos** [Stanvk/Magister#6]
Hi,

When trying to install your package I run into the following error:
    - stanvk/magister dev-master requires filp/whoops ^1.2@dev -> no matching package found.

When I look at  the whoops package (https://packagist.org/packages/filp/whoops) I also noticed the latest version is 1.1.6. Can you please fix this dependency?

Thanks!

**Comment by nielskramerr** [comment]
Also experiencing this issue

**Comment by Stanvk** [comment]
Binnenkort ga ik hier naar kijken. Voor nu zou je de code via Git kunnen clonen.
`git clone https://github.com/stanvk/magister.git`

Zorg dat Composer geupdate is! Dit kan door:
`composer self-update`

Nu kun je handmatig de dependencies binnenhalen.
`composer update`

Mocht het bovenstaande niet werken hoor ik het graag.
**Magister API is nog unstable. We zijn hard aan een stable build aan het werken!**

**Comment by JoeyHoutenbos** [comment]
Dit is niet echt een oplossing, want dan moet ik hem handmatig in m'n project gaan zetten. Daarnaast krijg ik bij iedere update dan ook weer dezelfde melding.
De oplossing zou zijn om niet de development versies van "filp/whoops" en "symfony/var-dumper" te gebruiken.
Verder is voor "symfony/var-dumper" ook een minimale PHP versie van 5.5.9 nodig. Veel servers draaien nog op een oudere versie van PHP dus lijkt me dit ook geen goed gekozen versie.

Het enige wat nodig is om dit op te lossen is de composer.json aanpassen zodat "filp/whoops" versie 1.1.6 gebruikt en "symfony/var-dumper" versie 2.7.1.

Door deze versies te gebruiken ondersteun je oudere PHP versies en kan "minimum-stability": "dev" weer terug naar "stable".

**Comment by Kickwood** [comment]
Had voorheen nog verder weinig aandacht besteed aan het Composer gedeelte, dus zeker prettig dat je het even aan de orde brengt. Heb even gekeken naar de correcte versies, naar jij zegt, en gezorgd dat het geheel nu geschikt is voor PHP 5.4.0. Ik neem aan dat het probleem nu opgelost is, maar ik heb verder nog niet de tijd gehad dit te controleren.

Wat betreft het daadwerkelijke gebruik van de API zou ik nog even wachten tot volgende week. We zijn momenteel bezig met het herschrijven van de authenticatie systemen waardoor het systeem nu even onbruikbaar is. Ik verwacht dit, en de bijhorende overige zaken, deze week af te hebben. Zodra dit af is kan uiteraard het hele systeem en diens functionaliteiten zonder problemen gebruikt worden.

Als verder nog iets niet naar behoren werkt, hetzij Composer, hetzij wat anders, dan hoor ik het graag!

**Comment by JoeyHoutenbos** [comment]
@Kickwood bedankt voor het doorvoeren van deze wijzigingen. Het installeren van de package gaat nu goed, maar misschien zou voor "filp/whoops" versie "1.1.*" nog mooier zijn. 
Ik zal afwachten tot begin volgende week, maar we hebben het wel echt nu nodig eigenlijk. Anders zullen we toch zelf via API-calls moeten gaan werken.

Ik hoor het graag als het authenticatie systeem is afgerond.

**Comment by Kickwood** [comment]
We zijn in principe klaar met het authenticatie systeem met uitzondering van een klein dingetje dat we vandaag zullen afronden. Het systeem is voor de rest helemaal stabiel. Verder zullen we gedurende deze week nog een aantal dingetjes aanpassen en toevoegen, maar dit zal het gebruik niet beïnvloeden.

**Comment by JoeyHoutenbos** [comment]
@Kickwood bedankt voor het doorgeven. En de timing is ook perfect! Morgen zal ik het allemaal gaan gebruiken...

**Comment by JoeyHoutenbos** [comment]
In composer.json hebben jullie nu "guzzle/guzzle": "~3.9" staan. Echter als ik op packagist.org kijk (https://packagist.org/packages/guzzle/guzzle) dan wordt deze package niet meer ondersteund. Ik vraag me dan ook af waarom deze gebruikt wordt?

**Comment by Kickwood** [comment]
De nieuwste versie van Guzzle (6) heeft PHP 5.5.0 nodig, terwijl wij uiteraard PHP 5.4.0 willen ondersteunen. Daarbij bevatten zowel versie 5 als versie 6 niet direct de benodigde functionaliteiten. Om deze versies dan toch te gebruiken, zouden we veel eigen code moeten schrijven; dit is gewoonweg te tijdrovend en ook geheel onnodig. Wat betreft versie 4 hebben wij op het eerste gezicht geen documentatie kunnen vinden, dus hier kunnen wij geen oordeel over vellen. Daarentegen heeft versie 3 wel een uitgebreide documentatie en bevat ook nog eens precies die dingen die wij nodig hebben. We hebben elke versie, met uitzondering van 4, uitgeprobeerd en we kwamen tot de conclusie dat versie 3 het beste voor ons werkt. We zullen hoe dan ook deze week nog even kijken hoe en wat met versie 4.
