### ISSUE TITLE
Leermiddelen

### ISSUE THREAD

**Issue by ItsMeRomian** [Stanvk/Magister#60]
Is er een manier om bij leermiddelen te komen? als ik `json_decode(Http::get("personen/$id/digitaallesmateriaal/Ean/EANCODE")->getBody());` gebruik krijg ik `NULL` terug, geen `invalid url` of `geen rechten`.

**Comment by Stanvk** [comment]
Als het goed is werkt deze URI wel: "/api/personen/$id/lesmateriaal"

**Comment by ItsMeRomian** [comment]
dankje!
