### ISSUE TITLE
Magister Update

### ISSUE THREAD

**Issue by MakerTim** [Stanvk/Magister#64]
Hey there,

It seems there was a Magister update recently,
My application runs for almost a year without a problem and now it got error's all over the place

`cURL error 60: SSL certificate problem: self signed certificate in certificate chain `

StackTrace
```#0 .\vendor\guzzlehttp\guzzle\src\RequestFsm.php(104): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
#1 .\vendor\guzzlehttp\guzzle\src\RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#2 .\vendor\react\promise\src\FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#3 .\vendor\guzzlehttp\ringphp\src\Future\CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#4 .\vendor\guzzlehttp\guzzle\src\Message\FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#5 .\vendor\guzzlehttp\guzzle\src\RequestFsm.php(135): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#6 .\vendor\guzzlehttp\guzzle\src\Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#7 .\vendor\guzzlehttp\guzzle\src\Client.php(135): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#8 .\vendor\stanvk\magister\src\Magister\Services\Auth\ElegantUserProvider.php(70): GuzzleHttp\Client->delete('sessies/huidige')
#9 .\vendor\stanvk\magister\src\Magister\Services\Auth\Guard.php(140): Magister\Services\Auth\ElegantUserProvider->retrieveByCredentials(Array)
#10 [internal function]: Magister\Services\Auth\Guard->attempt(Array)
#11 .\vendor\stanvk\magister\src\Magister\Services\Support\Manager.php(101): call_user_func_array(Array, Array)
#12 .\vendor\stanvk\magister\src\Magister\Services\Auth\AuthServiceProvider.php(45): Magister\Services\Support\Manager->__call('attempt', Array)
#13 .\vendor\stanvk\magister\src\Magister\Services\Auth\AuthServiceProvider.php(45): Magister\Services\Auth\AuthManager->attempt(Array)
#14 .\vendor\stanvk\magister\src\Magister\Magister.php(180): Magister\Services\Auth\AuthServiceProvider->boot()
#15 .\vendor\stanvk\magister\src\Magister\Magister.php(164): Magister\Magister->bootProvider(Object(Magister\Services\Auth\AuthServiceProvider))
#16 [internal function]: Magister\Magister->Magister\{closure}(Object(Magister\Services\Auth\AuthServiceProvider), 6)
#17 .\vendor\stanvk\magister\src\Magister\Magister.php(165): array_walk(Array, Object(Closure))
#18 .\vendor\stanvk\magister\src\Magister\Services\Foundation\Bootstrap\BootProviders.php(21): Magister\Magister->boot()
#19 .\vendor\stanvk\magister\src\Magister\Magister.php(104): Magister\Services\Foundation\Bootstrap\BootProviders->bootstrap(Object(Magister\Magister))
#20 .\vendor\stanvk\magister\src\Magister\Services\Foundation\Http\Kernel.php(50): Magister\Magister->bootstrapWith(Array)
#21 .\vendor\stanvk\magister\src\Magister\Magister.php(61): Magister\Services\Foundation\Http\Kernel->bootstrap()
#22 .\app\commands\MagisterImport.php(84): Magister\Magister->__construct('hermannwesselin...', '...', '...')
#23 .\app\commands\MagisterImport.php(44): MagisterImport->magisterImport(Object(Student))
#24 .\vendor\laravel\framework\src\Illuminate\Console\Command.php(112): MagisterImport->fire()
#25 .\vendor\symfony\console\Command\Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 .\vendor\laravel\framework\src\Illuminate\Console\Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 .\vendor\symfony\console\Application.php(843): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 .\vendor\symfony\console\Application.php(188): Symfony\Component\Console\Application->doRunCommand(Object(MagisterImport), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 .\vendor\symfony\console\Application.php(119): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 .\artisan(59): Symfony\Component\Console\Application->run()
#31 {main}
```

On my side:
```    public function fire()
    {

		foreach (Student::all() as $student) {
			if ($student->school->is_magister === 1) {
				$this->magisterImport($student);
			}
		}

    }
```
`$magister = new Magister\Magister($student->magister_link, $student->magister_username, $student->magister_password);`
Can login manually with credentials

I am on "stanvk/magister": "dev-master"

**Comment by CasperBr** [comment]
This is true. You must contact Magister to obtain access to their new API.

Op 11 jan. 2019, om 14:41 heeft Tim <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hey there,

It seems there was a Magister update recently,
My application runs for almost a year without a problem and now it got error's all over the place

cURL error 60: SSL certificate problem: self signed certificate in certificate chain

StackTrace

#1 .\vendor\guzzlehttp\guzzle\src\RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#2 .\vendor\react\promise\src\FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#3 .\vendor\guzzlehttp\ringphp\src\Future\CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#4 .\vendor\guzzlehttp\guzzle\src\Message\FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#5 .\vendor\guzzlehttp\guzzle\src\RequestFsm.php(135): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#6 .\vendor\guzzlehttp\guzzle\src\Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#7 .\vendor\guzzlehttp\guzzle\src\Client.php(135): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#8 .\vendor\stanvk\magister\src\Magister\Services\Auth\ElegantUserProvider.php(70): GuzzleHttp\Client->delete('sessies/huidige')
#9 .\vendor\stanvk\magister\src\Magister\Services\Auth\Guard.php(140): Magister\Services\Auth\ElegantUserProvider->retrieveByCredentials(Array)
#10 [internal function]: Magister\Services\Auth\Guard->attempt(Array)
#11 .\vendor\stanvk\magister\src\Magister\Services\Support\Manager.php(101): call_user_func_array(Array, Array)
#12 .\vendor\stanvk\magister\src\Magister\Services\Auth\AuthServiceProvider.php(45): Magister\Services\Support\Manager->__call('attempt', Array)
#13 .\vendor\stanvk\magister\src\Magister\Services\Auth\AuthServiceProvider.php(45): Magister\Services\Auth\AuthManager->attempt(Array)
#14 .\vendor\stanvk\magister\src\Magister\Magister.php(180): Magister\Services\Auth\AuthServiceProvider->boot()
#15 .\vendor\stanvk\magister\src\Magister\Magister.php(164): Magister\Magister->bootProvider(Object(Magister\Services\Auth\AuthServiceProvider))
#16 [internal function]: Magister\Magister->Magister\{closure}(Object(Magister\Services\Auth\AuthServiceProvider), 6)
#17 .\vendor\stanvk\magister\src\Magister\Magister.php(165): array_walk(Array, Object(Closure))
#18 .\vendor\stanvk\magister\src\Magister\Services\Foundation\Bootstrap\BootProviders.php(21): Magister\Magister->boot()
#19 .\vendor\stanvk\magister\src\Magister\Magister.php(104): Magister\Services\Foundation\Bootstrap\BootProviders->bootstrap(Object(Magister\Magister))
#20 .\vendor\stanvk\magister\src\Magister\Services\Foundation\Http\Kernel.php(50): Magister\Magister->bootstrapWith(Array)
#21 .\vendor\stanvk\magister\src\Magister\Magister.php(61): Magister\Services\Foundation\Http\Kernel->bootstrap()
#22 .\app\commands\MagisterImport.php(84): Magister\Magister->__construct('hermannwesselin...', '...', '...')
#23 .\app\commands\MagisterImport.php(44): MagisterImport->magisterImport(Object(Student))
#24 .\vendor\laravel\framework\src\Illuminate\Console\Command.php(112): MagisterImport->fire()
#25 .\vendor\symfony\console\Command\Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 .\vendor\laravel\framework\src\Illuminate\Console\Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 .\vendor\symfony\console\Application.php(843): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 .\vendor\symfony\console\Application.php(188): Symfony\Component\Console\Application->doRunCommand(Object(MagisterImport), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 .\vendor\symfony\console\Application.php(119): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 .\artisan(59): Symfony\Component\Console\Application->run()
#31 {main}


On my side:

    {

                foreach (Student::all() as $student) {
                        if ($student->school->is_magister === 1) {
                                $this->magisterImport($student);
                        }
                }

    }```
`$magister = new Magister\Magister($student->magister_link, $student->magister_username, $student->magister_password);`
Can login manually with credentials

I am on "stanvk/magister": "dev-master"

**Comment by MakerTim** [comment]
Koen vandaag om 15:40
https://accounts.magister.net/connect/authorize?
client_id=M6-atscholen.magister.net&
redirect_uri=https%3A%2F%2Fatscholen.magister.net%2Foidc%2Fredirect_callback.html&
response_type=id_token%20token&
scope=openid%20profile%20magister.ecs.legacy%20magister.mdv.broker.read%20magister.dnn.roles.read&
state=44e1a5bfc286461a9ad585340143f62a&
nonce=9e73bbbc30e345b09b1814f4ae20e3c6&
acr_values=tenant%3Aatscholen.magister.net


Dit is eerste request je krijgt hier mee 2 cookies: XSRF-TOKEN en Magister.Identities.XSRF
Je krijgt ook een locatie als header terug, dit het tweede request.

https://accounts.magister.net/account/login?
returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DM6-atscholen.magister.net%26redirect_uri%3Dhttps%253A%252F%252Fatscholen.magister.net%252Foidc%252Fredirect_callback.html%26response_type%3Did_token%2520token%26scope%3Dopenid%2520profile%2520magister.ecs.legacy%2520magister.mdv.broker.read%2520magister.dnn.roles.read%26state%3D44e1a5bfc286461a9ad585340143f62a%26nonce%3D9e73bbbc30e345b09b1814f4ae20e3c6%26acr_values%3Dtenant%253Aatscholen.magister.net


Tweede request bij dit request krijg je de sessionId en weer de cookies die je al had in vorige request.
En weer een locatie wat de volgende request is.

https://accounts.magister.net/account/login?
sessionId=a9851791e3854a7ab1ea34ab2ce710ab&
returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DM6-atscholen.magister.net%26redirect_uri%3Dhttps%253A%252F%252Fatscholen.magister.net%252Foidc%252Fredirect_callback.html%26response_type%3Did_token%2520token%26scope%3Dopenid%2520profile%2520magister.ecs.legacy%2520magister.mdv.broker.read%2520magister.dnn.roles.read%26state%3D44e1a5bfc286461a9ad585340143f62a%26nonce%3D9e73bbbc30e345b09b1814f4ae20e3c6%26acr_values%3Dtenant%253Aatscholen.magister.net


Derde request je krijg hier geen bruikbare data van.(gewijzigd)
https://accounts.magister.net/challenge/current


HEADERS
Content-Type = application/json
X-XSRF-TOKEN = (dit is de XSRF-TOKEN cookie die je bij de vorige requeste hebt gekregen)


BODY
{
    "sessionId":"sessionId van request drie",
    "returnUrl":"returnURL die je in het derde request hebt gekregen"
}
MakerTimvandaag om 15:45
waarom is deze shizzel zo giga uitgebreid
Koen vandaag om 15:46
ikr
return url kon ik ook niet aan passen na iets als localhost
je moet 4e request nog 2x uitvoeren(gewijzigd)
eerste keer met "username":"USERNAME"
tweede keer met "password":"PASSWORD"
in de json(body)
MakerTimvandaag om 15:47
los?
Koen vandaag om 15:47
ja
heel irritant
3e request is post btw
en laaste request is GET op de return url van request 3/4/5/6(gewijzigd)
MakerTimvandaag om 15:49
;-;

Koen vandaag om 15:50
en dan heb je een bearer token weer in location header van dat reqeust
en die moet je voortaan gebruiken in alle requesten ipv sessionid
de api zelf is niet veranderd voor wat ik weet, alleen sessionid naar bearer token
