### ISSUE TITLE
Extending Data Models

### ISSUE THREAD

**Issue by nielskramerr** [Stanvk/Magister#7]
Hello,

I would like to request the implementation of two new datamodals. Namingly 
- The courses 
- Column specific information

The courses are required to attach a grade to a specific course since the "Omschrijving" field in the individual grades is null. The url for retreiving the courses would be like :
/api/personen/{id}/aanmeldingen/{enrollment}/vakken

Also the column specific information is required to get the weight of the grades. This information can be retrieved through:
api/personen/{id}/aanmeldingen/{enrollment}/cijfers/extracijferkolominfo/{gradeid}

Currently i wrote the config and the models myself for a quick fix. But would be nice to see this implemented obviously.

Greetings,,

Niels

**Comment by Kickwood** [comment]
Getting column specific information is already possible through model relationships. You can either call `info()` on the grade model or call the info property. The `info()` method retrieves an instance of an info model based on the grade id. The info property accesses the `info()` method through a magic method and calls `first()` on the info model. A few examples:

``` php
Grade::find(1)->info;
```

Is the same as:

``` php
Grade::find(1)->info()->first();
```

You can loop through all the grades:

``` php
foreach (Grade::all() as $grade)
{
    echo $grade->info()->pluck('Weging');
}
```

You can use the info model directly as well:

``` php
Info::where('CijferKolom.Id', $id)->first();
```

You can work with this any way you want.
