### ISSUE TITLE
Ending a session

### ISSUE THREAD

**Issue by joep-nl** [Stanvk/Magister#8]
Is it possible to end a session/logout the user? And how?

**Comment by Stanvk** [comment]
The [Guard](https://github.com/Stanvk/Magister/blob/master/src/Magister/Services/Auth/Guard.php)  takes care of authentication and allows to authenticate a Magister account. In order to end a session, you can use the Auth surrogate which is in fact a wrapper for the Guard.

``` php
<?php

require 'vendor/autoload.php';

use Magister\Magister;

//Notice
use Auth;

$magiser = new Magister($school, $username, $password);

//Log the user out.
Auth::logout();
```
